name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  update_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: make auth
        env:
          D8Y_AUTH_CACHE_DATA: ${{ secrets.D8Y_AUTH_CACHE_DATA }}
      - id: capture_auth_cache_data
        run: echo "AUTH_CACHE_DATA=$(cat $GITHUB_WORKSPACE/tests/data/auth)" >> $GITHUB_OUTPUT
      - uses: gliech/create-github-secret-action@v1
        with:
          name: D8Y_AUTH_CACHE_DATA
          value: ${{ steps.capture_auth_cache_data.outputs.AUTH_CACHE_DATA }}
          pa_token: ${{ secrets.GH_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: make lint

  test:
    runs-on: ubuntu-latest
    needs: update_secret
    strategy:
      # TODO: Playlist title is the same for all tests, which would make tests clash with each other
      max-parallel: 1
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: make ci
        env:
          D8Y_AUTH_CACHE_DATA: ${{ secrets.D8Y_AUTH_CACHE_DATA }}
      - uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.11'
